#!/usr/bin/env python

import sys
import os
import shutil


def load_grab_dirs():
    grab_dirs = os.environ.get("GRAB_PATH", "").split(":")
    return grab_dirs


def grab_file(file, grab_dirs):
    for dir_to_grab_from in grab_dirs:
        grab_path = os.path.join(dir_to_grab_from, file)
        if os.path.isfile(grab_path):
            shutil.copy(grab_path, os.getcwd())
            return
    print(f"Cannot find file in GRAB_PATH: {file}")


def main(files_to_grab, grab_dirs):
    for file in files_to_grab:
        grab_file(file, grab_dirs)


if __name__ == "__main__":
    main(sys.argv[1:], load_grab_dirs())
